import Card from "@/components/elements/Card"
import ScrollExpandCard from "@/components/elements/ScrollExpandCard"
import AboutMe from "@/composites/home/AboutMe"
import Summary from "@/composites/home/Summary"
import useIntersectionObserver from "@/hooks/useIntersectionObserver"
import Head from "next/head"
import { useEffect, useState, useRef } from "react"

const X_COORDINATE_LEFT = 40
const X_COORDINATE_CENTER = 310.25
const X_COORDINATE_RIGHT = 580.5

const THRESHOLD = 10

const X_INTERSECTION_START = 300

const leftContent = <p className="text-2xl font-bold italic">Currently working at:</p>
const rightContent = (
  <>
    <p className="text-4xl font-bold italic">Erajaya</p>
    <p className="text-lg">September 2022 - Present</p>
  </>
)

export default function Home() {
  return (
    <>
      <Head>
        <title>@ramadhanabs | Personal Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-black p-10 grid grid-flow-row">
        <div className="hidden sm:block absolute top-[24px] left-[24px]">
          <img className="w-32 h-32 animate-spin-slow" src="circular-text.svg" />
        </div>
        <div className="flex justify-center py-[100px]">
          <img src="logo.svg" alt="svg" className="w-[300px]" />
        </div>
        <Summary />
        <AboutMe />
        <div className="h-[2000px]">
          <ScrollExpandCard
            startCoordinate={X_INTERSECTION_START}
            leftContent={leftContent}
            rightContent={rightContent}
          />
          <ScrollExpandCard
            startCoordinate={X_INTERSECTION_START + 300 * 1}
            leftContent={leftContent}
            rightContent={rightContent}
          />
          <ScrollExpandCard
            startCoordinate={X_INTERSECTION_START + 300 * 2}
            leftContent={leftContent}
            rightContent={rightContent}
          />
        </div>
      </div>
    </>
  )
}
