import Footer from "@/components/elements/Footer"
import ScrollExpandCard from "@/components/elements/ScrollExpandCard"
import AboutMe from "@/composites/home/AboutMe"
import Summary from "@/composites/home/Summary"
import Head from "next/head"

const X_INTERSECTION_START = 300
const CONTENT_HEIGHT = 300

const EXPANDABLE_CONTENT = [
  {
    left: <p className="text-2xl font-bold italic">Currently working at:</p>,
    right: (
      <>
        <p className="text-4xl font-bold italic">Erajaya</p>
        <p className="text-lg">September 2022 - Present</p>
      </>
    ),
  },
  {
    left: <p className="text-2xl font-bold italic">My motto:</p>,
    right: (
      <>
        <p className="text-4xl font-bold italic">Manners Maketh Man.</p>
      </>
    ),
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>@ramadhanabs | Personal Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-black p-10 grid grid-flow-row">
        <div className="hidden sm:block absolute top-[24px] left-[24px]">
          <img className="w-32 h-32 animate-spin-slow" src="circular-text.svg" />
        </div>
        <div className="flex justify-center py-[100px]">
          <img src="logo.svg" alt="svg" className="w-[300px]" />
        </div>
        <Summary />
        <AboutMe />
        <div className="h-[2000px]">
          {EXPANDABLE_CONTENT.map((content, index) => (
            <ScrollExpandCard
              startCoordinate={X_INTERSECTION_START + CONTENT_HEIGHT * index}
              leftContent={content.left}
              rightContent={content.right}
              key={index}
            />
          ))}
        </div>
        <Footer />
      </div>
    </>
  )
}
